project:
  type: website
  output-dir: docs #move this here

website:
  title: "Portfolio"
  site-url: "https://laurag49-49.github.io/Porfolio"
  repo-url: "https://github.com/laurag49-49/Portfolio"
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



