project:
  type: website
  output-dir: docs #move this here

website:
  title: "Portfolio"
  site-url: "https://laurag49-49.github.io/Porfolio"
  repo-url: "https://github.com/laurag49-49/Portfolio"
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Test1.qmd
        text: about me

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

#git add docs
#git commit -m "Render Quarto site to docs and add .nojekyll"
#git push

#git add docs/.nojekyll
#git add -f docs  # force add if it’s being ignored
#git commit -m "Add .nojekyll to disable Jekyll"
#git push

